// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mimo.ApiClient.MimoApi.Tenant.Configuration;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mimo.ApiClient.MimoApi.Tenant
{
    /// <summary>
    /// Builds and executes requests for operations under \tenant
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TenantRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The configuration property</summary>
        public global::Mimo.ApiClient.MimoApi.Tenant.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::Mimo.ApiClient.MimoApi.Tenant.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Tenant.TenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tenant", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Tenant.TenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tenant", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
