// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mimo.ApiClient.MimoApi.Tickets.Claim;
using Mimo.ApiClient.MimoApi.Tickets.Close;
using Mimo.ApiClient.MimoApi.Tickets.Detail;
using Mimo.ApiClient.MimoApi.Tickets.My;
using Mimo.ApiClient.MimoApi.Tickets.Notes;
using Mimo.ApiClient.MimoApi.Tickets.Queue;
using Mimo.ApiClient.MimoApi.Tickets.Reopen;
using Mimo.ApiClient.MimoApi.Tickets.Resolve;
using Mimo.ApiClient.MimoApi.Tickets.Transfer;
using Mimo.ApiClient.MimoApi.Tickets.Visible;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mimo.ApiClient.MimoApi.Tickets
{
    /// <summary>
    /// Builds and executes requests for operations under \tickets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TicketsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The claim property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Claim.ClaimRequestBuilder Claim
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Claim.ClaimRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The close property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Close.CloseRequestBuilder Close
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Close.CloseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The detail property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Detail.DetailRequestBuilder Detail
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Detail.DetailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The my property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.My.MyRequestBuilder My
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.My.MyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notes property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Notes.NotesRequestBuilder Notes
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Notes.NotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queue property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Queue.QueueRequestBuilder Queue
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Queue.QueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reopen property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Reopen.ReopenRequestBuilder Reopen
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Reopen.ReopenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resolve property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder Resolve
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transfer property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Transfer.TransferRequestBuilder Transfer
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Transfer.TransferRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The visible property</summary>
        public global::Mimo.ApiClient.MimoApi.Tickets.Visible.VisibleRequestBuilder Visible
        {
            get => new global::Mimo.ApiClient.MimoApi.Tickets.Visible.VisibleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Tickets.TicketsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TicketsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tickets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Tickets.TicketsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TicketsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tickets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
