// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Mimo.ApiClient.MimoApi.Documents.Detail;
using Mimo.ApiClient.MimoApi.Documents.Reindex;
using Mimo.ApiClient.MimoApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mimo.ApiClient.MimoApi.Documents
{
    /// <summary>
    /// Builds and executes requests for operations under \documents
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DocumentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The detail property</summary>
        public global::Mimo.ApiClient.MimoApi.Documents.Detail.DetailRequestBuilder Detail
        {
            get => new global::Mimo.ApiClient.MimoApi.Documents.Detail.DetailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reindex property</summary>
        public global::Mimo.ApiClient.MimoApi.Documents.Reindex.ReindexRequestBuilder Reindex
        {
            get => new global::Mimo.ApiClient.MimoApi.Documents.Reindex.ReindexRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/documents{?categoryId*,isActive*,roleId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/documents{?categoryId*,isActive*,roleId*}", rawUrl)
        {
        }
        /// <summary>
        /// Desactiva un documento / borrado lógico (query: id).
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lista documentos del tenant con filtros opcionales.
        /// </summary>
        /// <returns>A List&lt;global::Mimo.ApiClient.MimoApi.Models.DocumentResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse>?> GetAsync(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse>> GetAsync(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse>(requestInfo, global::Mimo.ApiClient.MimoApi.Models.DocumentResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Crea un documento y genera su embedding para búsqueda semántica.
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Models.DocumentResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse?> PostAsync(global::Mimo.ApiClient.MimoApi.Models.CreateDocumentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse> PostAsync(global::Mimo.ApiClient.MimoApi.Models.CreateDocumentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse>(requestInfo, global::Mimo.ApiClient.MimoApi.Models.DocumentResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Actualiza un documento; regenera embedding si cambia el contenido (query: id).
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Models.DocumentResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse?> PutAsync(global::Mimo.ApiClient.MimoApi.Models.UpdateDocumentRequest body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse> PutAsync(global::Mimo.ApiClient.MimoApi.Models.UpdateDocumentRequest body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Mimo.ApiClient.MimoApi.Models.DocumentResponse>(requestInfo, global::Mimo.ApiClient.MimoApi.Models.DocumentResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Desactiva un documento / borrado lógico (query: id).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, "{+baseurl}/documents?id={id}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Lista documentos del tenant con filtros opcionales.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Crea un documento y genera su embedding para búsqueda semántica.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Mimo.ApiClient.MimoApi.Models.CreateDocumentRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Mimo.ApiClient.MimoApi.Models.CreateDocumentRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Actualiza un documento; regenera embedding si cambia el contenido (query: id).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Mimo.ApiClient.MimoApi.Models.UpdateDocumentRequest body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Mimo.ApiClient.MimoApi.Models.UpdateDocumentRequest body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder.DocumentsRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, "{+baseurl}/documents?id={id}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mimo.ApiClient.MimoApi.Documents.DocumentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Desactiva un documento / borrado lógico (query: id).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DocumentsRequestBuilderDeleteQueryParameters 
        {
            [QueryParameter("id")]
            public Guid? Id { get; set; }
        }
        /// <summary>
        /// Lista documentos del tenant con filtros opcionales.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DocumentsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("categoryId")]
            public Guid? CategoryId { get; set; }
            [QueryParameter("isActive")]
            public bool? IsActive { get; set; }
            [QueryParameter("roleId")]
            public Guid? RoleId { get; set; }
        }
        /// <summary>
        /// Actualiza un documento; regenera embedding si cambia el contenido (query: id).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DocumentsRequestBuilderPutQueryParameters 
        {
            [QueryParameter("id")]
            public Guid? Id { get; set; }
        }
    }
}
#pragma warning restore CS0618
