// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mimo.ApiClient.MimoApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BusinessHoursConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The businessHoursEnabled property</summary>
        public bool? BusinessHoursEnabled { get; set; }
        /// <summary>The endTime property</summary>
        public Time? EndTime { get; set; }
        /// <summary>The outOfHoursMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutOfHoursMessage { get; set; }
#nullable restore
#else
        public string OutOfHoursMessage { get; set; }
#endif
        /// <summary>The startTime property</summary>
        public Time? StartTime { get; set; }
        /// <summary>The workingDays property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? WorkingDays { get; set; }
#nullable restore
#else
        public List<int?> WorkingDays { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig"/> and sets the default values.
        /// </summary>
        public BusinessHoursConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "businessHoursEnabled", n => { BusinessHoursEnabled = n.GetBoolValue(); } },
                { "endTime", n => { EndTime = n.GetTimeValue(); } },
                { "outOfHoursMessage", n => { OutOfHoursMessage = n.GetStringValue(); } },
                { "startTime", n => { StartTime = n.GetTimeValue(); } },
                { "workingDays", n => { WorkingDays = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("businessHoursEnabled", BusinessHoursEnabled);
            writer.WriteTimeValue("endTime", EndTime);
            writer.WriteStringValue("outOfHoursMessage", OutOfHoursMessage);
            writer.WriteTimeValue("startTime", StartTime);
            writer.WriteCollectionOfPrimitiveValues<int?>("workingDays", WorkingDays);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
