// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mimo.ApiClient.MimoApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TenantConfiguration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The agentIntervention property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mimo.ApiClient.MimoApi.Models.AgentInterventionConfig? AgentIntervention { get; set; }
#nullable restore
#else
        public global::Mimo.ApiClient.MimoApi.Models.AgentInterventionConfig AgentIntervention { get; set; }
#endif
        /// <summary>The businessHours property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig? BusinessHours { get; set; }
#nullable restore
#else
        public global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig BusinessHours { get; set; }
#endif
        /// <summary>The channelCustomization property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mimo.ApiClient.MimoApi.Models.ChannelCustomizationConfig? ChannelCustomization { get; set; }
#nullable restore
#else
        public global::Mimo.ApiClient.MimoApi.Models.ChannelCustomizationConfig ChannelCustomization { get; set; }
#endif
        /// <summary>The customerAttention property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mimo.ApiClient.MimoApi.Models.CustomerAttentionConfig? CustomerAttention { get; set; }
#nullable restore
#else
        public global::Mimo.ApiClient.MimoApi.Models.CustomerAttentionConfig CustomerAttention { get; set; }
#endif
        /// <summary>The satisfactionSurvey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mimo.ApiClient.MimoApi.Models.SatisfactionSurveyConfig? SatisfactionSurvey { get; set; }
#nullable restore
#else
        public global::Mimo.ApiClient.MimoApi.Models.SatisfactionSurveyConfig SatisfactionSurvey { get; set; }
#endif
        /// <summary>The sessionAssignment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mimo.ApiClient.MimoApi.Models.SessionAssignmentConfig? SessionAssignment { get; set; }
#nullable restore
#else
        public global::Mimo.ApiClient.MimoApi.Models.SessionAssignmentConfig SessionAssignment { get; set; }
#endif
        /// <summary>The transfers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mimo.ApiClient.MimoApi.Models.TransfersConfig? Transfers { get; set; }
#nullable restore
#else
        public global::Mimo.ApiClient.MimoApi.Models.TransfersConfig Transfers { get; set; }
#endif
        /// <summary>The unattendedSessions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig? UnattendedSessions { get; set; }
#nullable restore
#else
        public global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig UnattendedSessions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Models.TenantConfiguration"/> and sets the default values.
        /// </summary>
        public TenantConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Models.TenantConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mimo.ApiClient.MimoApi.Models.TenantConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mimo.ApiClient.MimoApi.Models.TenantConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agentIntervention", n => { AgentIntervention = n.GetObjectValue<global::Mimo.ApiClient.MimoApi.Models.AgentInterventionConfig>(global::Mimo.ApiClient.MimoApi.Models.AgentInterventionConfig.CreateFromDiscriminatorValue); } },
                { "businessHours", n => { BusinessHours = n.GetObjectValue<global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig>(global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig.CreateFromDiscriminatorValue); } },
                { "channelCustomization", n => { ChannelCustomization = n.GetObjectValue<global::Mimo.ApiClient.MimoApi.Models.ChannelCustomizationConfig>(global::Mimo.ApiClient.MimoApi.Models.ChannelCustomizationConfig.CreateFromDiscriminatorValue); } },
                { "customerAttention", n => { CustomerAttention = n.GetObjectValue<global::Mimo.ApiClient.MimoApi.Models.CustomerAttentionConfig>(global::Mimo.ApiClient.MimoApi.Models.CustomerAttentionConfig.CreateFromDiscriminatorValue); } },
                { "satisfactionSurvey", n => { SatisfactionSurvey = n.GetObjectValue<global::Mimo.ApiClient.MimoApi.Models.SatisfactionSurveyConfig>(global::Mimo.ApiClient.MimoApi.Models.SatisfactionSurveyConfig.CreateFromDiscriminatorValue); } },
                { "sessionAssignment", n => { SessionAssignment = n.GetObjectValue<global::Mimo.ApiClient.MimoApi.Models.SessionAssignmentConfig>(global::Mimo.ApiClient.MimoApi.Models.SessionAssignmentConfig.CreateFromDiscriminatorValue); } },
                { "transfers", n => { Transfers = n.GetObjectValue<global::Mimo.ApiClient.MimoApi.Models.TransfersConfig>(global::Mimo.ApiClient.MimoApi.Models.TransfersConfig.CreateFromDiscriminatorValue); } },
                { "unattendedSessions", n => { UnattendedSessions = n.GetObjectValue<global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig>(global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.AgentInterventionConfig>("agentIntervention", AgentIntervention);
            writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.BusinessHoursConfig>("businessHours", BusinessHours);
            writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.ChannelCustomizationConfig>("channelCustomization", ChannelCustomization);
            writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.CustomerAttentionConfig>("customerAttention", CustomerAttention);
            writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.SatisfactionSurveyConfig>("satisfactionSurvey", SatisfactionSurvey);
            writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.SessionAssignmentConfig>("sessionAssignment", SessionAssignment);
            writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.TransfersConfig>("transfers", Transfers);
            writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig>("unattendedSessions", UnattendedSessions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
