// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mimo.ApiClient.MimoApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TicketResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignedAgentId property</summary>
        public Guid? AssignedAgentId { get; set; }
        /// <summary>The assignedAt property</summary>
        public DateTimeOffset? AssignedAt { get; set; }
        /// <summary>The assignedRoleId property</summary>
        public Guid? AssignedRoleId { get; set; }
        /// <summary>The channel property</summary>
        public int? Channel { get; set; }
        /// <summary>The conversationId property</summary>
        public Guid? ConversationId { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The customerName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerName { get; set; }
#nullable restore
#else
        public string CustomerName { get; set; }
#endif
        /// <summary>The escalationReason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EscalationReason { get; set; }
#nullable restore
#else
        public string EscalationReason { get; set; }
#endif
        /// <summary>The firstResponseAt property</summary>
        public DateTimeOffset? FirstResponseAt { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The internalNotes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalNotes { get; set; }
#nullable restore
#else
        public string InternalNotes { get; set; }
#endif
        /// <summary>The lastMessageAt property</summary>
        public DateTimeOffset? LastMessageAt { get; set; }
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The queuePosition property</summary>
        public int? QueuePosition { get; set; }
        /// <summary>The resolvedAt property</summary>
        public DateTimeOffset? ResolvedAt { get; set; }
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Models.TicketResponse"/> and sets the default values.
        /// </summary>
        public TicketResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Models.TicketResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mimo.ApiClient.MimoApi.Models.TicketResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mimo.ApiClient.MimoApi.Models.TicketResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignedAgentId", n => { AssignedAgentId = n.GetGuidValue(); } },
                { "assignedAt", n => { AssignedAt = n.GetDateTimeOffsetValue(); } },
                { "assignedRoleId", n => { AssignedRoleId = n.GetGuidValue(); } },
                { "channel", n => { Channel = n.GetIntValue(); } },
                { "conversationId", n => { ConversationId = n.GetGuidValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customerName", n => { CustomerName = n.GetStringValue(); } },
                { "escalationReason", n => { EscalationReason = n.GetStringValue(); } },
                { "firstResponseAt", n => { FirstResponseAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "internalNotes", n => { InternalNotes = n.GetStringValue(); } },
                { "lastMessageAt", n => { LastMessageAt = n.GetDateTimeOffsetValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "queuePosition", n => { QueuePosition = n.GetIntValue(); } },
                { "resolvedAt", n => { ResolvedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("assignedAgentId", AssignedAgentId);
            writer.WriteDateTimeOffsetValue("assignedAt", AssignedAt);
            writer.WriteGuidValue("assignedRoleId", AssignedRoleId);
            writer.WriteIntValue("channel", Channel);
            writer.WriteGuidValue("conversationId", ConversationId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("customerName", CustomerName);
            writer.WriteStringValue("escalationReason", EscalationReason);
            writer.WriteDateTimeOffsetValue("firstResponseAt", FirstResponseAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("internalNotes", InternalNotes);
            writer.WriteDateTimeOffsetValue("lastMessageAt", LastMessageAt);
            writer.WriteIntValue("priority", Priority);
            writer.WriteIntValue("queuePosition", QueuePosition);
            writer.WriteDateTimeOffsetValue("resolvedAt", ResolvedAt);
            writer.WriteIntValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
