// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mimo.ApiClient.MimoApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransferTicketRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contextNote property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContextNote { get; set; }
#nullable restore
#else
        public string ContextNote { get; set; }
#endif
        /// <summary>The isPartial property</summary>
        public bool? IsPartial { get; set; }
        /// <summary>The reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The toAgentId property</summary>
        public Guid? ToAgentId { get; set; }
        /// <summary>The toRoleId property</summary>
        public Guid? ToRoleId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Models.TransferTicketRequest"/> and sets the default values.
        /// </summary>
        public TransferTicketRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Models.TransferTicketRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mimo.ApiClient.MimoApi.Models.TransferTicketRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mimo.ApiClient.MimoApi.Models.TransferTicketRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contextNote", n => { ContextNote = n.GetStringValue(); } },
                { "isPartial", n => { IsPartial = n.GetBoolValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "toAgentId", n => { ToAgentId = n.GetGuidValue(); } },
                { "toRoleId", n => { ToRoleId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("contextNote", ContextNote);
            writer.WriteBoolValue("isPartial", IsPartial);
            writer.WriteStringValue("reason", Reason);
            writer.WriteGuidValue("toAgentId", ToAgentId);
            writer.WriteGuidValue("toRoleId", ToRoleId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
