// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mimo.ApiClient.MimoApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UnattendedSessionsConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autoRetry property</summary>
        public bool? AutoRetry { get; set; }
        /// <summary>The timeoutAction property</summary>
        public int? TimeoutAction { get; set; }
        /// <summary>The timeoutCustomerMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeoutCustomerMessage { get; set; }
#nullable restore
#else
        public string TimeoutCustomerMessage { get; set; }
#endif
        /// <summary>The unattendedTimeoutMinutes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? UnattendedTimeoutMinutes { get; set; }
#nullable restore
#else
        public UntypedNode UnattendedTimeoutMinutes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig"/> and sets the default values.
        /// </summary>
        public UnattendedSessionsConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Mimo.ApiClient.MimoApi.Models.UnattendedSessionsConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoRetry", n => { AutoRetry = n.GetBoolValue(); } },
                { "timeoutAction", n => { TimeoutAction = n.GetIntValue(); } },
                { "timeoutCustomerMessage", n => { TimeoutCustomerMessage = n.GetStringValue(); } },
                { "unattendedTimeoutMinutes", n => { UnattendedTimeoutMinutes = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autoRetry", AutoRetry);
            writer.WriteIntValue("timeoutAction", TimeoutAction);
            writer.WriteStringValue("timeoutCustomerMessage", TimeoutCustomerMessage);
            writer.WriteObjectValue<UntypedNode>("unattendedTimeoutMinutes", UnattendedTimeoutMinutes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
