// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Mimo.ApiClient.MimoApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mimo.ApiClient.MimoApi.Webhooks.Incoming
{
    /// <summary>
    /// Builds and executes requests for operations under \webhooks\incoming
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IncomingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IncomingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks/incoming?channel={channel}{&hub%2Echallenge*,hub%2Emode*,hub%2Everify_token*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IncomingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks/incoming?channel={channel}{&hub%2Echallenge*,hub%2Emode*,hub%2Everify_token*}", rawUrl)
        {
        }
        /// <summary>
        /// Verificación del endpoint de webhook para Meta; el proveedor se configura con ?channel= (query).
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder.IncomingRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder.IncomingRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Recibe y procesa mensajes entrantes de un canal externo (query: channel).
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(global::Mimo.ApiClient.MimoApi.Models.IKeyedServiceProvider body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder.IncomingRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(global::Mimo.ApiClient.MimoApi.Models.IKeyedServiceProvider body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder.IncomingRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Verificación del endpoint de webhook para Meta; el proveedor se configura con ?channel= (query).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder.IncomingRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder.IncomingRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Recibe y procesa mensajes entrantes de un canal externo (query: channel).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Mimo.ApiClient.MimoApi.Models.IKeyedServiceProvider body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder.IncomingRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Mimo.ApiClient.MimoApi.Models.IKeyedServiceProvider body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder.IncomingRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mimo.ApiClient.MimoApi.Webhooks.Incoming.IncomingRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Verificación del endpoint de webhook para Meta; el proveedor se configura con ?channel= (query).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IncomingRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("channel")]
            public string? Channel { get; set; }
#nullable restore
#else
            [QueryParameter("channel")]
            public string Channel { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("hub%2Echallenge")]
            public string? HubChallenge { get; set; }
#nullable restore
#else
            [QueryParameter("hub%2Echallenge")]
            public string HubChallenge { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("hub%2Emode")]
            public string? HubMode { get; set; }
#nullable restore
#else
            [QueryParameter("hub%2Emode")]
            public string HubMode { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("hub%2Everify_token")]
            public string? HubVerifyToken { get; set; }
#nullable restore
#else
            [QueryParameter("hub%2Everify_token")]
            public string HubVerifyToken { get; set; }
#endif
        }
        /// <summary>
        /// Recibe y procesa mensajes entrantes de un canal externo (query: channel).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IncomingRequestBuilderPostQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("channel")]
            public string? Channel { get; set; }
#nullable restore
#else
            [QueryParameter("channel")]
            public string Channel { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
