// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Mimo.ApiClient.MimoApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mimo.ApiClient.MimoApi.Tickets.Resolve
{
    /// <summary>
    /// Builds and executes requests for operations under \tickets\resolve
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResolveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResolveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tickets/resolve?id={id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResolveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tickets/resolve?id={id}", rawUrl)
        {
        }
        /// <summary>
        /// Marca el ticket como resuelto (query: id).
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolvePostRequestBody body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolveRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolvePostRequestBody body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolveRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Marca el ticket como resuelto (query: id).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolvePostRequestBody body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolveRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolvePostRequestBody body, Action<RequestConfiguration<global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolveRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Mimo.ApiClient.MimoApi.Models.UpdateTicketNotesRequest"/>, <see cref="global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolvePostRequestBodyMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ResolvePostRequestBody : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolvePostRequestBodyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolvePostRequestBodyMember1? ResolvePostRequestBodyMember1 { get; set; }
#nullable restore
#else
            public global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolvePostRequestBodyMember1 ResolvePostRequestBodyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Mimo.ApiClient.MimoApi.Models.UpdateTicketNotesRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Mimo.ApiClient.MimoApi.Models.UpdateTicketNotesRequest? UpdateTicketNotesRequest { get; set; }
#nullable restore
#else
            public global::Mimo.ApiClient.MimoApi.Models.UpdateTicketNotesRequest UpdateTicketNotesRequest { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolvePostRequestBody"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolvePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolveRequestBuilder.ResolvePostRequestBody();
                if("UpdateTicketNotesRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UpdateTicketNotesRequest = new global::Mimo.ApiClient.MimoApi.Models.UpdateTicketNotesRequest();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ResolvePostRequestBodyMember1 != null)
                {
                    return ResolvePostRequestBodyMember1.GetFieldDeserializers();
                }
                else if(UpdateTicketNotesRequest != null)
                {
                    return UpdateTicketNotesRequest.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ResolvePostRequestBodyMember1 != null)
                {
                    writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Tickets.Resolve.ResolvePostRequestBodyMember1>(null, ResolvePostRequestBodyMember1);
                }
                else if(UpdateTicketNotesRequest != null)
                {
                    writer.WriteObjectValue<global::Mimo.ApiClient.MimoApi.Models.UpdateTicketNotesRequest>(null, UpdateTicketNotesRequest);
                }
            }
        }
        /// <summary>
        /// Marca el ticket como resuelto (query: id).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ResolveRequestBuilderPostQueryParameters 
        {
            [QueryParameter("id")]
            public Guid? Id { get; set; }
        }
    }
}
#pragma warning restore CS0618
