// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Mimo.ApiClient.MimoApi.InternalChat.History;
using Mimo.ApiClient.MimoApi.InternalChat.Read;
using Mimo.ApiClient.MimoApi.InternalChat.Send;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mimo.ApiClient.MimoApi.InternalChat
{
    /// <summary>
    /// Builds and executes requests for operations under \internal-chat
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InternalChatRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The history property</summary>
        public global::Mimo.ApiClient.MimoApi.InternalChat.History.HistoryRequestBuilder History
        {
            get => new global::Mimo.ApiClient.MimoApi.InternalChat.History.HistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The read property</summary>
        public global::Mimo.ApiClient.MimoApi.InternalChat.Read.ReadRequestBuilder Read
        {
            get => new global::Mimo.ApiClient.MimoApi.InternalChat.Read.ReadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The send property</summary>
        public global::Mimo.ApiClient.MimoApi.InternalChat.Send.SendRequestBuilder Send
        {
            get => new global::Mimo.ApiClient.MimoApi.InternalChat.Send.SendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.InternalChat.InternalChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InternalChatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/internal-chat", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mimo.ApiClient.MimoApi.InternalChat.InternalChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InternalChatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/internal-chat", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
